### ISSUE TITLE
shortcode for theme.php?

### ISSUE THREAD

**Issue by kreossino** [e107inc/multilan#11]
what's the shortcode for insert a multilan_flags directly in the theme.php?

**Comment by rica-carv** [comment]
MULTILAN_NAV????

**Comment by kreossino** [comment]
I search the shortcode {MULTILAN_CODE}? whats?

**Comment by rica-carv** [comment]
[MULTILAN_NAV](https://github.com/e107inc/multilan/blob/master/e_shortcode.php#L15), not MULTILAN_CODE!

>  Language navigation is now sorted correctly. Global {MULTILAN_NAV} shortcode added for use in theme footers.
> https://github.com/e107inc/multilan/commit/86b7962c711aeeb781e475ce5ac0c57c1d0f99af
