### ISSUE TITLE
LAN_MULTILAN_NAVICON displayed in UI

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/multilan#14]
Hi @CaMer0n 
Uploaded the new version today :)  
I'm seeing LAN_MULTILAN_NAVICON in the UI Admin >Prefs > Navigation >  Main Navigation Icon > Hover Text. 
There's no "languages" folder, hence, where should multilan LANs be defined? And what tip text were you thinking of? 
Thanks
Mikey

**Comment by MikeyGMT** [comment]
Oops, maybe this is duplicate of #12

**Comment by CaMer0n** [comment]
It's not a bug. Use it in the Sitelinks to have it auto-replaced by the icon and dropdown.
