### ISSUE TITLE
Creates a Language Link with sub items for Each Language, but without a Link Name

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/multilan#3]
On install it creates a link for each language, which appears in the main links but is missing the Link Name, hence is hidden in the front end UI. Adding a link name makes the menu appear and allows the end user to choose their prefered lan. 

![image](https://cloud.githubusercontent.com/assets/2847651/8315375/4912b628-19e8-11e5-88f9-b44493ce0cc7.png)

Unlike the Admin Lan option it appears in the main links area rather than on the right with the signup/logon menu (bootstrap).

**Comment by CaMer0n** [comment]
@MikeyGMT - it should have inserted an icon (instead of a name) for the link. I just re-tested and this is what it does for me. Does it still occur for you?
