### ISSUE TITLE
MultiLan > News / Pages > With Selected > Action List is empty

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/multilan#4]
Hi Dev's
When you go to the news or pages list, you cannot action the copy to the multilan tables.
Thanks
Mike

**Comment by MikeyGMT** [comment]
More info: The main News application seems to do the copying, as long as the category exists in the foreign lan. Then edit from Foreign Admin Area > News and on additional tab change class from TRANSLATE_ME

**Comment by CaMer0n** [comment]
Yes, eventually the actions should include "Copy to X" (Where X is the language installed). One entry for each language.

**Comment by CaMer0n** [comment]
This has been completed.
