### ISSUE TITLE
Multiple Languages>Tools>Generate Lans (Links)

### ISSUE THREAD

**Issue by MikeyGMT** [e107inc/multilan#5]
Hi Dev's,
OK I tested the links generator tool.

"This will generate LAN definitions for all your sitelinks and store them in a custom language file within your system folder and then update all your link names to use them."

Not really sure what the purpose is ....  It works, except for in Admin, if you are likely to update your site links a lot, it's not so friendly for the admin. I found the custom lan file here e107_system/x1Y2z3/lans/English_custom.php it is working. 

![image](https://cloud.githubusercontent.com/assets/2847651/8343729/5ac53b1e-1ad0-11e5-809b-1724f6297516.png)

Initial feeling is that it would be better to just copy the EN links to the XX tables, not seeing the advantage of putting link names into a custom lan file. 

What does the prefs>offline>redirect do?

Thanks

Mikey

**Comment by CaMer0n** [comment]
It Allows an admin to maintain a single links table, instead of mutliple ones. 
Offline redirect, lets you redirect or 'close for maintenance' specific languages on your site. 
ie. you could have one language 'live' while the other is offline.
