### ISSUE TITLE
How to use different sitle links for each language?

### ISSUE THREAD

**Issue by lonalore** [e107inc/multilan#7]
I use "Profile aliases" like:
![kepernyokep - 2016-03-21 - 14 25 42](https://cloud.githubusercontent.com/assets/6043821/13920194/15d0117e-ef72-11e5-8617-9e9235b2b82f.png)

And one of my site links:
![kepernyokep - 2016-03-21 - 14 26 55](https://cloud.githubusercontent.com/assets/6043821/13920208/254a2ce8-ef72-11e5-9795-d7886960e80d.png)

I would like to use "hirek" link for hungarian language, and "news" for english. How can I set this?

**Comment by Norwayman** [comment]
Excelent idea @lonalore

**Comment by lonalore** [comment]
I can achive this by enabling multilan DB tables, so I close this now. :)
